### ISSUE TITLE
Now Have Anomaly For Stock Location Column

### ISSUE THREAD

**Issue by LarryJoy** [inventree/InvenTree.github.io#53]
When I look at "Stock" list of parts the Location column has "No stock location set" or "Undefined location". Yet when I go to the "Parts", pick on a part that I have quantity of, and go to "edit", a location is stated. I think this happened with the new update.
--Larry

**Comment by SchrodingersGat** [comment]
Hi Larry, can you please share a screenshot of the two cases so I know exactly where to look?

**Comment by LarryJoy** [comment]
Here are the two screenshots:
![image](https://user-images.githubusercontent.com/18520951/83828949-cdc5c780-a6af-11ea-9915-4d8e17bf5a5f.png)
![image](https://user-images.githubusercontent.com/18520951/83829158-39a83000-a6b0-11ea-995c-65e5824a095a.png)
I hope the screenshots are big enough to see the text. If not I can take a screenshot of a smaller area.
--Larry

**Comment by SchrodingersGat** [comment]
Ah, I see - you are conflating two concepts here (which is understandable, given the current level of documentation)

## Part - Default Location

The "Part" object has a default location - this is nominally the location where any stock of that part are stored. A part does not need to have a default location set.

## Stock - Location

The "Stock" object has a location set - this is where a particular stock item is situated. This may be different to the default location set for the corresponding Part

## Example

### New Stock Item

![image](https://user-images.githubusercontent.com/10080325/83858861-77649180-a760-11ea-8ef7-62513205daed.png)

### Select Base Part

![image](https://user-images.githubusercontent.com/10080325/83858938-9400c980-a760-11ea-9381-9bd50f0aaa3a.png)

### Select Location

![image](https://user-images.githubusercontent.com/10080325/83859030-b2ff5b80-a760-11ea-8961-69e414297067.png)

### Set Stock Quantity

![image](https://user-images.githubusercontent.com/10080325/83859083-c7435880-a760-11ea-86ac-25df3d9bad8f.png)

**Comment by LarryJoy** [comment]
Okay, Thanks Oliver.
--Larry
