### ISSUE TITLE
Terminology Difference

### ISSUE THREAD

**Issue by LarryJoy** [inventree/InvenTree.github.io#56]
Hello,
Under "Create new Stock Item" you have "Base Part", yet under "Create New Supplier Part" you use the term "Part" and it turns out to be same thing. This was confusing to me at first. Suggest using the same term in both places, probably "Base Part".
--Regards, Larry

**Comment by SchrodingersGat** [comment]
Thanks Larry - this is now addressed in https://github.com/inventree/InvenTree/pull/867

BTW - if you have issues related to the documentation (inventree.github.io) then they should be posted *here*, but issues related to InvenTree functionality should be posted over at https://github.com/inventree/inventree/issues
