### ISSUE TITLE
Inventory Value of Part List Table Items

### ISSUE THREAD

**Issue by LarryJoy** [inventree/InvenTree.github.io#57]
Hi Guys (and any Gals),
I am now entering Parts and Stock information from my previous P&V6.0 inventory program into InvenTree and I am having a problem with how to enter the per piece cost of an item. According to GAAP (Generally Accepted Accounting Principles) and IRS rules, the inventory cost of an item, what would be the COGS (cost of goods sold) is based on the cost of the item from the supplier, plus any tariff, plus any shipping charge, and where applicable any sales or use tax paid. I don't see anywhere in InvenTree where to enter that number when calculated and which number would carry over to any BOM cost calculation.

An example would be a resistor from supplier Mouser and manufacturer Ohmite. The price breaks are as follows:
1 @ $0.10/EA
10 @ $0.017/EA
25 @ $0.015/EA
50 @ $0.013/EA
100 @ $0.011/EA
I now have 9 of these in my stock at a previously calculated $0.01836/EA (to the nearest 5th decimal place) = $0.165224 total cost or value. One way around this would be to change the price break of 1 to the calculated per piece value, but if you are using the calculated value in a purchase order you are going to be high in your base price costing.
--Regards, Larry

**Comment by SchrodingersGat** [comment]
Inventree does not have the complex accounting features you're looking for here, I'm afraid. Its primary intended purpose is tracking inventory, and I don't have the bandwidth to add these other features. If you (or someone else who is keen for such a feature) wants to help implement this, I'd love that! It sounds like a great addition.

**Comment by LarryJoy** [comment]
Oliver,
I am not a programmer or software engineer so I can not help with any programming. For now I will either have to keep using my P&V6.0 program, which I believe is based on Microsoft database and looks like a spreadsheet wherein the inventory value column is the inventory quantity column multiplied by the cost per each column. For the total cost of the inventory you just do a summation of the inventory value column. Or I am going to have to do a separate spreadsheet to keep track of costs.

Please put the implementation of these two pieces of financial information, the total cost of inventory and the COGS for an assembly (BOM), at the top of your to do list. And, again, thanks for your work and making InvenTree available.
--Larry
