### ISSUE TITLE
Return to Active Status

### ISSUE THREAD

**Issue by LarryJoy** [inventree/InvenTree.github.io#60]
I won't go in to why I set a part to Inactive, but I now want to reset the part to Active. How do I do that? Clicking on the icon does nothing, it stays "Inactive".
--Thanks and regards, Larry

**Comment by LarryJoy** [comment]
**[Solved]** Never mind, I found it--under Admin.
--Larry

**Comment by SchrodingersGat** [comment]
Hi Larry,

For reference, here's the button you'd want to use to toggle part active status:

![image](https://user-images.githubusercontent.com/10080325/85943190-bfe32980-b971-11ea-9e79-fe81b5eae26f.png)

**Comment by LarryJoy** [comment]
That button does not work to set "Active" back to "Yes" (Part is active) once it is used to set "Active" to "No". As I stated I had to go into the "Admin" functions to set it back to "Yes" (Part is active).
--Larry

**Comment by SchrodingersGat** [comment]
I recently addressed a bug related to this - try updating to the latest revision and see if it works for you. Cheers
