### ISSUE TITLE
Move documentation to Python MkDocs + Material Theme?

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree.github.io#66]
@SchrodingersGat I started looking into this repo to write about the new color theme feature and realized it is disconnected from the Pythonic spirit of your other repos, with the Ruby/Jekyll setup being required to run the site locally.
Have you considered running it with the [MkDocs Python server](https://www.mkdocs.org/#installation)?  
And using the [MkDocs Material theme](https://squidfunk.github.io/mkdocs-material/getting-started/) instead of the Jekyll version?

I'm happy to make the move, but I wanted to know if there was a good reason not to do so :thinking: 

Even with that, I'm still thinking the entry level for writing InvenTree docs is pretty overwhelming for anybody motivated but with low to no programming skills.
I understand Github provides free storage for static pages and that's awesome. But have you thought of getting a domain name and moving the doc website to [Wagtail](https://wagtail.io/) instead? I'm renting a shared server that I use for [my website](https://eeinte.ch/stream/) which uses Wagtail + coderedcms (Bootstrap plugin) to run all my articles and it works pretty nicely. Wagtail has a moderation pipeline so that any contribution can be reviewed by the site admins before being published.

There are probably other options out there too which I'm not aware of, this is only food for thoughts :wink:

**Comment by SchrodingersGat** [comment]
Interesting option. I've also been considering migrating to [readthedocs.io](https://docs.readthedocs.io/en/stable/development/install.html)

(which is incidentally where the [InvenTree source code documentation](https://inventree.readthedocs.io/en/latest/) is already being served)

## Advantages

- Free
- Python / Django based (I didn't actually realize this!)
- Documentation could be in the same repo as the source, and updated whenever a PR is made
- Uses markdown (or rst but I much prefer markdown)
-  Easier for contribution (both easier to setup, and more "in-line" with pythonic feel)

## Disadvantages

- Have to migrate everything...

What do you think of a readthedocs approach?

**Comment by eeintech** [comment]
It looks like Readthedocs supports MkDocs [out-of-the-box](https://docs.readthedocs.io/en/stable/intro/getting-started-with-mkdocs.html) so migration shouldn't be too hard, I've actually built the docs with MkDocs + Material theme mentioned above and the result wasn't far off.

> Easier for contribution (both easier to setup, and more "in-line" with pythonic feel)

It feels to me that the contribution side would **not** be made easier (comparing with Github Pages), one would still have to fork the doc repository to add anything. Or am I missing some information here?

> Documentation could be in the same repo as the source, and updated whenever a PR is made

Indeed, that would mean re-purposing the `docs` folder serving https://inventree.readthedocs.io/ for this documentation. I'm not quite certain what you'd want to keep from https://inventree.readthedocs.io/, still I don't think it would be too hard to merge.
On the other hand, moving the docs to the InvenTree source repo might throw off some contributors, as one would have to fork the entire source code and docs to simply modify some markdown files... feels a little cumbersome.

**Comment by eeintech** [comment]
@SchrodingersGat I went and gave a shot to Mkdocs Material, would you mind having a look to see if you like it?

```
git clone -b mkdocs_material git@github.com:eeintech/InvenTree.github.io.git
cd InvenTree.github.io/
python3 -m venv env
source env/bin/activate
pip install -r requirements.txt
mkdocs serve
```
And navigate to http://127.0.0.1:8000

I only implemented the home, contribute and getting started pages.

**Comment by SchrodingersGat** [comment]
This is fantastic, I really like how it looks.

It appears that using mkdocs means that we can still use github pages? https://www.mkdocs.org/user-guide/deploying-your-docs/

**Comment by eeintech** [comment]
Yes, it is definitely compatible, I'll try to make sure it is formatted right before sending the PR.

I'm glad you like it, I'll continue my effort to migrate the rest of the pages 😃

**Comment by eeintech** [comment]
Migration is done, created PR #67
